"""empty message

Revision ID: 1135dd28899b
Revises: e8bc16f98a7f
Create Date: 2024-07-14 15:24:45.781391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1135dd28899b'
down_revision = 'e8bc16f98a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.drop_column('glug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glug', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
