"""empty message

Revision ID: 383f57e1d303
Revises: b21401f77c3d
Create Date: 2024-07-16 16:38:44.977245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383f57e1d303'
down_revision = 'b21401f77c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
