"""empty message

Revision ID: 540b296213ba
Revises: 00e88ce20839
Create Date: 2024-07-14 14:35:05.452420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '540b296213ba'
down_revision = '00e88ce20839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
